### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by GrahamRCT** [ikhanage/Glicko2#3]
Since in many jurisdictions copyright is automatic, people can not know what terms they have to abide if they wish to use this code. Glicko itself is public domain, so this C# implementation may be licensed any way the author desires. There's no requirement for this project to also be public domain.

Please clarify your position, so that people (including myself) know how they can include this code into their projects.

**Comment by ikhanage** [comment]
It's public. Use as you want, in any way you want.

**Comment by GrahamRCT** [comment]
Thanks, I really only made the issue because I couldn't find your contact information. Sorry if this is unhandy.

**Comment by ikhanage** [comment]
No that's exactly what this is for.  Hope your project goes well :)
